### ISSUE TITLE
Feature Request - Toolbar button and global hotkey to toggle rainbow colorization

### ISSUE THREAD

**Issue by jhigh2000** [madskristensen/RainbowBraces#1]
Thanks for this extension! As the title states, a toolbar button/global hotkey to toggle the colorization on/off would be a very welcome feature, if possible.

**Comment by gpshonik** [comment]
One of the recent updates seems to have caused a regression on this feature.  When the colorization is toggled off, any code editing activity turns the colorization back on and it takes several hotkey invocations to turn it back off.

**Comment by madskristensen** [comment]
@gpshonik thanks for the heads up. This is now fixed and a new release is making its way through the CI process right now.
