### ISSUE TITLE
Enable vertical lines in parenthesis

### ISSUE THREAD

**Issue by weitzhandler** [madskristensen/RainbowBraces#103]
This is super useful in functional style C# where there long nested lambda expressions. It's also super useful when writing [C# Markup](https://github.com/VincentH-Net/CSharpForMarkup).

**Comment by lordfanger** [comment]
Hi,
if I understand it right, you want to show vertical line adornments like this?
![image](https://github.com/madskristensen/RainbowBraces/assets/17590847/3c74a55f-5bf7-47e8-a68e-9c4ff3346893)

If so, it'll be for VS feedback suggestion. Once implemented, it'll be colorized by this extension out of the box the same way the curly bracket blocks are now.

If I'm wrong, can you send some screenshots what do you want?

**Comment by weitzhandler** [comment]
Yes that's what I meant. I'm gonna close this issue then. Should I open or find a similar issue, I'll link it in here.

**Comment by weitzhandler** [comment]
https://developercommunity.visualstudio.com/t/Enable-vertical-guidelines-for-parenthes/10442432

I hope you don't mind that I used your picture. Will gladly credit you or delete it.

**Comment by lordfanger** [comment]
> https://developercommunity.visualstudio.com/t/Enable-vertical-guidelines-for-parenthes/10442432
> 
> I hope you don't mind that I used your picture. Will gladly credit you or delete it.

You were faster than me I were about to create the ticket myself with reference to you ^^

Anyway I took that screenshot from C# markup readme ;)
