### ISSUE TITLE
Ability to keep cycle length of parentheses/square brackets separate from curly brackets

### ISSUE THREAD

**Issue by Josh-Heaps** [madskristensen/RainbowBraces#108]
**Is your feature request related to a problem? Please describe.**
I like to use rainbow braces for a couple of different reasons. First, it helps me keep track of what I have and haven't closed. Second, I can use it to see, at a glance, how deeply nested code is. The problem arrives when a method is being passed a headless method (some kind of delegate), the parentheses for the method call will increase the cycle depth, and then the curly brackets inside are a deeper depth than if it was just an if statement. 

**Describe the solution you'd like**
Example: In this picture, I'd like the parentheses to be the starting color, and both sets of curly brackets to be green. If possible, adding an option for multiple cycles, with different lengths, and different colors would be nice, but I understand if that's asking for too much.
![image](https://github.com/madskristensen/RainbowBraces/assets/146474968/4432fa55-2d88-4948-8183-5cbc83e6d368)

**Describe alternatives you've considered**
I've tried using the new feature added to VS, where they have default bracket coloring, but that doesn't look as nice as your extension does. I'm going to use it either way, but it would be nice to have the additional feature.

**Comment by lordfanger** [comment]
If you want (), {}, [] and <> to not interfere with each other, it should be possible. For a while it was implemented but considered a bug and reworked to use the same "cycle stack" for all.
