### ISSUE TITLE
Change the default colors so there are no red or gray

### ISSUE THREAD

**Issue by carlosmunozrodriguez** [madskristensen/RainbowBraces#112]
Default colors shouldn't be red or gray.

By default the Rainbow Brace Level 2 is red which may make the editor look like there are errors.

Also levels 8 and 9 are shadows of gray which look like they are redundant and can be refactored out.

As an example: This is a screenshot of code with the default colors

![with red or gray](https://github.com/madskristensen/RainbowBraces/assets/4722957/999382bc-0fa8-469f-bae3-48acc39ca34f)

And this is the same code after color changes

![without red or gray](https://github.com/madskristensen/RainbowBraces/assets/4722957/fd29f2e0-b6a8-453f-be61-69c00928b8cb)

Environment:

- Visual Studio Enterprise 2022 Version 17.10.0
- Default Dark theme

**Comment by carlosmunozrodriguez** [comment]
Thanks guys, I can get rid of my personalization now.
I don't want to be pushy but looking at the code, the colors were originally coming from resistors color code.
It was probably some arbitrary convention to have a starting point but no longer seems to be applicable.

The comments relating to the resistor color code could be removed or changed somehow.

**Comment by lordfanger** [comment]
Yeah, I planned it, but later I did some refactor and forget to remove the comments. Maybe when I remember later, I'll do it.
