### ISSUE TITLE
Visual Studio hangs on commenting out lines in Razor view

### ISSUE THREAD

**Issue by Fandermill** [madskristensen/RainbowBraces#12]
**Describe the bug**
Today I installed the extension in my VS2022 (17.3.3) and all worked fine. Until I needed to change and comment out some lines in a Razor view in a ASP.Net Framework MVC project. When typing `@*`, VS automatically adds `*@`, but the first time it takes a few seconds. Then, the next time, or the third, VS goes from hanging to freezing.

The Razor view I worked on contains `if/else` statements and thus multiple braces. Which do not get colored, by the way.

After trying and freezing a couple of times, I disabled the extension and commenting out a line in a Razor view worked again. That's why I'm filing a bug report, because I think this is related to the extension.
Re-enabling the extension and trying again, causes the problem again.

**To Reproduce**
1. Enable RainbowBraces extension
2. Open an existing Razor view (cshtml)
3. Try to comment out a few lines by inserting `@*` at the start of the line to comment.
4. Then cut the automatically added `*@` and paste it to the end of the line
5. Repeat 3 & 4 until it hangs and freezes.

**Expected behavior**
I expected the Razor editor to work as before installing the extension.

**Comment by madskristensen** [comment]
Does this reproduce with the latest version of the extension?

**Comment by ScottDatafest** [comment]
I am also getting an issue with VS freezing when RainbowBraces is enabled, when opening Razor (cshtml) files.  In my case it's happened with various .cshtml files and seems unrelated to comments since I don't have any comments in this particular file.

I'm running version 1.0.18

I'd be happy to supply some examples if it would help.

**Comment by madskristensen** [comment]
@ScottDatafest what .NET version is your project using? Also, are you using the new experimental Razor editor that you have enabled under Preview Features in Tools/Options?

**Comment by ScottDatafest** [comment]
.Net Framework 4.7.2
Not using the new experimental Razor editor.

I am using ReSharper, version 2022.2.2.  (I’ll update ReSharper just to see if it makes any difference.)


Scott A. Clawson
President                         | Datafest Technologies, Inc.<http://www.datafest.com/>
(801) 261-4608 ext. 2  | AdSystem Blog<http://blog.datafest.com/>
[AdSystem Online Small]
