### ISSUE TITLE
Unable to compile - missing "VSGlobals.vsct"

### ISSUE THREAD

**Issue by LexaGV** [madskristensen/RainbowBraces#14]
I downloaded latest sources, opened project in VS. Then replaced nuget "System.ComponentModel.Composition" on local DLL (hope it's not a problem?). And when I tried to compile, first I got error " Your project does not reference ".NETFramework,Version=v4.8" - it's first fail of MS VS2022. After deleting bin/obj I compiled again and got "File not found: Unable to locate 'VSGlobals.vsct' on the include paths provided [r:\RainbowBraces-master\src\RainbowBraces.csproj".
I checked file and it's really missing. Why? Does anybody check that sources are compillable after fetching from repo?

**Comment by madskristensen** [comment]
The project does target .NET 4.8. It sounds like there is a nuget restore issue
