### ISSUE TITLE
Missing options

### ISSUE THREAD

**Issue by LexaGV** [madskristensen/RainbowBraces#15]
In a project README there is pic with extension options. They have items like "Colorize curly brackets", but when I installed extension in my VS2022 Ent, I found no such options just this: https://i.ibb.co/q5WfsNS/rainbow-failure.webp

**Comment by madskristensen** [comment]
You have an older version of the extension installed. When you update it to the latest version, you should see those options

**Comment by LexaGV** [comment]
@madskristensen : Yes, Mad, thanks, just discovered that! BUT... I took that version from MS "marketplace" - keep it updated, plz.
Despite I made project compillable (taking all nugets offline) I still got error when extension was installed: VS complained it cannot load some type (and as usual in MS style GIVE YOU ZERO INFO which type). Pity people screw up projects making 'em nuget-depended - normal practice is NOT to involve in development untested libraries.
