### ISSUE TITLE
Missing Color on bracets with noting inn it

### ISSUE THREAD

**Issue by BM0B0T** [madskristensen/RainbowBraces#2]
**Describe the bug**
missing colors on empty (), [] and {}.

**To Reproduce**
1. call a C# function with no parameters, it will be white.

**Expected behavior**
Should have color matching a function with parameters.

**Screenshots**
![image](https://user-images.githubusercontent.com/24739853/186651434-7ab54f74-a761-4d37-81da-089889eba6a7.png)

**Comment by madskristensen** [comment]
This is actually by design. I thought it would add unnecessary colors.

**Comment by andrekoehler** [comment]
I would prefer empty braces to not be colored. IMO it makes the code too colorful without any benefit. Maybe add an option for this?
