### ISSUE TITLE
Typing delay in text editor

### ISSUE THREAD

**Issue by aimi617** [madskristensen/RainbowBraces#21]
**Describe the bug**
The extension causes a typing delay on large C# files (usually more than 5000 lines).

**To Reproduce**
1. Install the extension on VS 2022.
2. Open a large .cs file, starting from 5000 lines and higher, there is a significant delay in typing. For example, on a file of approximately 9000 lines each key pressing gives a delay of few secs.

**Expected behavior**
After disabling the extension the typing comes to normal with no delay.

**Comment by FloydAtProwave** [comment]
I have the same experience. The .cs file has more than 10K lines. After disabled the extension, the typing becomes normal.

**Comment by butras** [comment]
Yes, I confirm even an HTML file of 338 lines (17.7 KB) where there are no brackets, VS 2022 gets completely stuck.

**Comment by FerranMG** [comment]
Same here on a `cpp` file of 8000+ lines. It's very difficult to work with this file.

**Comment by aimi617** [comment]
Last commit didn't resolve an issue, still the same problem (v1.0.28), large typing delay which makes coding miserable on large files.

**Comment by aimi617** [comment]
Thanks Mads, now looks good, I think it's an optimal solution to have "Max line length" in settings. Is any chance to colorize .js and .sql files?
