### ISSUE TITLE
Rainbow options are not found with a search filter

### ISSUE THREAD

**Issue by bveldkamp** [madskristensen/RainbowBraces#22]
To find out what the configuration options for RB are, I opened Tools > Options, and typed *rain* in the *Search Options* box. Nothing was found. Later, I noticed that the options are there, under Environment > Fonts and Colors.

Please add support for the search capability of the Options dialog.

![image](https://user-images.githubusercontent.com/7160755/190574748-37328ca8-c10a-48ae-b48c-0271b8d0cd8c.png)

**Comment by madskristensen** [comment]
I talked to @gundermanc and it seems to be an issue with VS not recognizing options pages 3 levels deep. I opened [a bug](https://developercommunity.visualstudio.com/t/Tools---Options-search-doesnt-find-pag/10150569?space=8&q=rainbow&ftype=problem&sort=newest) on it - make sure to vote.
