### ISSUE TITLE
Also colorize "generics" angle brackets, like Task<Foo<List<Baz>,Bar>>

### ISSUE THREAD

**Issue by hdkesting** [madskristensen/RainbowBraces#23]
**Is your feature request related to a problem? Please describe.**
For deeply nested generics, figuring out the right <> pair may be as difficult as for nested braces and brackets.

**Describe the solution you'd like**
Treat < and > (when used in generic types, not in XML comment tags or as comparison - less than/greater than) the same as {},(), [], so also include it in the color cycling. No need to set up a different cycle for these specifically.

**Comment by MiniverCheevy** [comment]
I was about to enter an issue requesting this feature

**Comment by WolfgangVogl** [comment]
I installed the latest version (1.0.88) in Visual Studio (version 17.5.1) - but the angles are still not colored (I tried with C++ code...).

For example this code:

template <type name T>
using TimeModeT = std::disjunction<std::is_same<T, UtcTime>, std::is_same<T, LocalTime>>;

No colors for < and >.
