### ISSUE TITLE
Breakpoint on brace interferes with nesting levels

### ISSUE THREAD

**Issue by bmadtiger** [madskristensen/RainbowBraces#31]
When a breakpoint is placed on an opening or closing curly brace (ie beginning or end of a block of code in C#), then that brace is ignored in calculating the nesting level.

Here the default orange for the first level of braces (on the class) is now being used for the methods and the end of the class is left uncolored.
![devenv_2022-09-28_20-44-11](https://user-images.githubusercontent.com/49149264/192766553-eca403c8-4e8e-4d9c-87a2-503a6f2b52d7.png)

Moving the breakpoint down one line resolves the issue
![devenv_2022-09-28_20-46-04](https://user-images.githubusercontent.com/49149264/192766642-c6998d21-ac24-4642-bea4-17f3e0e1d8eb.png)

**Comment by SkyGen** [comment]
FYI: I've seen this behavior on the latest (1.0.57) version. To repro, put a breakpoint on a starting or ending brace, then use the mouse wheel to scroll lines. Removing the breakpoint reveals the uncolored brace. Scrolling again recolors as expected.
