### ISSUE TITLE
Failure on load - Could not load file or assembly Community.VisualStudio.Toolkit

### ISSUE THREAD

**Issue by sandejd1** [madskristensen/RainbowBraces#32]
**Describe the bug**
When I open a solution, I get a prompt that RainbowBracesPackage did not load correctly.

**To Reproduce**
1. Open VS 2022 and choose Create a new project
2. Select 'Class Library' with C#. Next.
3. Keep defaults. Next.
4. Keep .NET 6.0. Create.
5. After a short time, screenshot appears.

**Expected behavior**
Package should load without errors.

**Screenshots**
![image](https://user-images.githubusercontent.com/30264745/193072077-54785b16-fd01-4926-bdd7-8ccdc2d8d5a8.png)

**Additional context**
Rainbow Braces v1.0.37

ActivityLog.xml
`<entry>
    <record>1431</record>
    <time>2022/09/29 15:28:50.087</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>CreateInstance failed for package [RainbowBracesPackage]Source: &apos;mscorlib&apos; Description: Could not load file or assembly &apos;Community.VisualStudio.Toolkit, Version=17.0.430.0, Culture=neutral, PublicKeyToken=79441d341a79572c&apos; or one of its dependencies. The system cannot find the file specified.&#x000D;&#x000A;System.IO.FileNotFoundException: Could not load file or assembly &apos;Community.VisualStudio.Toolkit, Version=17.0.430.0, Culture=neutral, PublicKeyToken=79441d341a79572c&apos; or one of its dependencies. The system cannot find the file specified.&#x000D;&#x000A;File name: &apos;Community.VisualStudio.Toolkit, Version=17.0.430.0, Culture=neutral, PublicKeyToken=79441d341a79572c&apos;&#x000D;&#x000A;   at System.Reflection.RuntimeAssembly.GetType(RuntimeAssembly assembly, String name, Boolean throwOnError, Boolean ignoreCase, ObjectHandleOnStack type)&#x000D;&#x000A;   at System.Reflection.RuntimeAssembly.GetType(String name, Boolean throwOnError, Boolean ignoreCase)&#x000D;&#x000A;   at System.Activator.CreateInstanceFromInternal(String assemblyFile, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityInfo)&#x000D;&#x000A;   at System.AppDomain.CreateInstanceFrom(String assemblyFile, String typeName)&#x000D;&#x000A;&#x000D;&#x000A;WRN: Assembly binding logging is turned OFF.&#x000D;&#x000A;To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.&#x000D;&#x000A;Note: There is some performance penalty associated with assembly bind failure logging.&#x000D;&#x000A;To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].&#x000D;&#x000A;</description>
    <guid>{8EB8A1E7-610C-47EC-B867-A8B500937F99}</guid>
    <hr>0x80004005 - E_FAIL</hr>
    <errorinfo></errorinfo>
  </entry>`

**Comment by madskristensen** [comment]
That looks like an installation issue. Is it fixed if you uninstall and reinstall the extension?

**Comment by sandejd1** [comment]
You are absolutely correct.  I think I did it to myself while trying to figure out some designer issues 😳.  Thanks for your help!
