### ISSUE TITLE
Doen not seem to work on PowerShell .ps1 and .psm1 files

### ISSUE THREAD

**Issue by PaulaScholz** [madskristensen/RainbowBraces#5]
**Is your feature request related to a problem? Please describe.**
It does not seem to work on PowerShell .ps1 and .psm1 files.

**Describe the solution you'd like**
I wish it would.

On C# it's awesome, thank you!

**Comment by madskristensen** [comment]
Fixed in latest version. However, the way Powershell files are classified, only some of the braces/brackets are colorized.

**Comment by PaulaScholz** [comment]
Confirmed to work on the braces, but not the parentheses nor brackets.
