### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by madskristensen** [madskristensen/RainbowBraces#61]
We have a callstack showing some threads going crazy in the extension:

<pre style="box-sizing: border-box; white-space: pre; overflow-wrap: normal; background-color: rgba(var(--palette-neutral-8,234, 234, 234),1); padding: 15px; overflow-x: auto; color: rgba(0, 0, 0, 0.9); font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><code style="box-sizing: border-box; font-family: Menlo, Consolas, &quot;Courier New&quot;, monospace; font-size: 12px; background-color: rgba(var(--palette-neutral-8,234, 234, 234),1); padding: 0px;">

Name
--
\|\|  + mscorlib.ni!ThreadPoolWorkQueue.Dispatch$##6003CA8
\|\|   + mscorlib.ni!IThreadPoolWorkItem.ExecuteWorkItem$##6003CC9
\|\|    + mscorlib.ni!System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.Run()$##6006FC7
\|\|     + mscorlib.ni!ExecutionContext.Run$##6003AEF
\|\|      + mscorlib.ni!ExecutionContext.RunInternal$##6003AF0
\|\|       + RainbowBraces!RainbowBraces.RainbowTagger+<ParseAsync>d__25.MoveNext()
\|\|       \|+ RainbowBraces!BracePairBuilderCollection.SaveToCache
\|\|       \| + mscorlib!System.Collections.Generic.Dictionary`2[System.ValueTuple`2[System.Char,System.Char],System.__Canon].Insert(!0,!1,bool)

</code></pre><br class="Apple-interchange-newline">

It looks like we are saving to cache too frequently.

@lordfanger what do you think?

**Comment by lordfanger** [comment]
Looks more like concurrency issue. Default dictionary capacity is 3. I've added fourth pair ('<' and '>') and then the dictionary can be in corrupted state and can end in infinite loop.

The `SaveToCache()` should be called once per `ParseAsync()` and set up to 4 entries.

I'll have a look.

**Comment by davkean** [comment]
Our Visual Studio telemetry that monitors high-CPU also captured this problem, thanks for the fix @lordfanger!

**Comment by lordfanger** [comment]
I'm sorry I read the callstack wrong. The problem was in async await method (`RainbowBraces!RainbowBraces.RainbowTagger+d__25.MoveNext()`). And somehow I overlooked it previously. It should be fixed now in #66.
