### ISSUE TITLE
Braces and brackets are not coloured in vbhtml or html files

### ISSUE THREAD

**Issue by graymatter00** [madskristensen/RainbowBraces#72]
Braces, brackets and vertical lines are not coloured in vbhtml  or regular html files.  See screenshots below.  All other files seem to be coloured as expected.

vbhtml file...

![image](https://github.com/madskristensen/RainbowBraces/assets/7201626/186acfb5-aaaf-46aa-b189-57947386e1f9)

![image](https://github.com/madskristensen/RainbowBraces/assets/7201626/d5397dda-2b20-43ef-8e52-95f9e1f997f2)

![image](https://github.com/madskristensen/RainbowBraces/assets/7201626/6056d4b8-576e-4d31-b0d5-0f1f875b1e23)

![image](https://github.com/madskristensen/RainbowBraces/assets/7201626/744524af-7ccf-4063-8c0e-3814cd2445ea)

![image](https://github.com/madskristensen/RainbowBraces/assets/7201626/1df047db-d591-42a0-a96c-d99fa4cc871f)

**Comment by graymatter00** [comment]
Unfortunately, it isn't working quite right.

![image](https://github.com/madskristensen/RainbowBraces/assets/7201626/9933388e-1465-4119-986a-6c7d42bc1d03)

Is this comment enough to re-open the issue or would you like me to create a new issue?

**Comment by lordfanger** [comment]
The `@Url.Action("Index", "Contact")` could be fixed in next release after merge #83
I'm not sure about the rest. It works ok i my test files. Can you attach whole files that don't work? Or are you using some other extension that can interfere? (custom HTML editor, another colorizer)

First screen looks like after first occurence of inline code it stops working.

**Comment by graymatter00** [comment]
@lordfanger  Yes, the new version containing merger #83 fixed the .vbhtml issue.  It's now coloured as I'd expect.  **Thanks!** 😊

The **.htm** files are still not being coloured.  I'll do some more checking and raise it as a separate issue in the next day or so.

🖖

**Comment by lordfanger** [comment]
Can you check it again with new version?

**Comment by lordfanger** [comment]
Sure, and try this.
Right click on .htm file and select option `Open With...` and post what editor is set as (Default).
There might be some editor that is not explicitly allowed by this extension. If it is so, it should be enabled by only a simple edit.

![image](https://github.com/madskristensen/RainbowBraces/assets/17590847/664f09d1-4a88-4ba3-b1fd-16877d5d1bec)
![image](https://github.com/madskristensen/RainbowBraces/assets/17590847/17eac397-5428-4b26-8d3f-9c8be09589a9)

**Comment by graymatter00** [comment]
@lordfanger Sorry for the delay in replying.  Life got in the way.

As requested, attached are two screenshots showing the **Open With** dialog window for both an existing .htm file and a newly created .html file.

![image](https://github.com/madskristensen/RainbowBraces/assets/7201626/a5b1b10c-d01f-416b-b593-6f80c2f15f2f)

![image](https://github.com/madskristensen/RainbowBraces/assets/7201626/ce952c9b-90bb-46d9-ab3a-506af16fcf77)

**Comment by lordfanger** [comment]
I don't see something suspicious. But added support for Web Forms in #92 PR. Maybe it could help if Mads merges it.
