### ISSUE TITLE
Add option to enable/disable rainbow colouring on certain types of braces

### ISSUE THREAD

**Issue by xEsteem** [madskristensen/RainbowBraces#8]
I do often find that with parentheses it’s hard to tell which opening and closing go together, but not really so much with curly braces.
It would be nice to have an option to enable/disable the rainbow colouring for certain types of braces. 

In my case I would disable it on curly braces but leave it enabled on parentheses for example.

**Comment by madskristensen** [comment]
Options added. Deploying to Marketplace now
